version: '3.8'
services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" 
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    restart: unless-stopped